echo "                   _           "
echo "  o               //           "
echo "  ,  _ _ _   _,  // _  , , _   "
echo "_/|_(_) / /_(_)_(/_(/_(_/_/ (_ "
echo " /)          /|                "
echo "(/          (/                 "
echo "                               "
